---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-machine-learning/resources/bANLa) course resource._

---

# Assignment 3 - Evaluation

In this assignment you will train several models and evaluate how effectively they predict instances of fraud using data based on [this dataset from Kaggle](https://www.kaggle.com/dalpozz/creditcardfraud).
 
Each row in `fraud_data.csv` corresponds to a credit card transaction. Features include confidential variables `V1` through `V28` as well as `Amount` which is the amount of the transaction. 
 
The target is stored in the `class` column, where a value of 1 corresponds to an instance of fraud and 0 corresponds to an instance of not fraud.

In [2]:
import numpy as np
import pandas as pd

### Question 1
Import the data from `fraud_data.csv`. What percentage of the observations in the dataset are instances of fraud?

*This function should return a float between 0 and 1.* 

In [3]:
def answer_one():
    
    df = pd.read_csv('fraud_data.csv')
    ts = df['Class'].value_counts(ascending=True)
    # Your code here
    return ts.loc[1]/ts.loc[0]# Return your answer ts.loc[1]/ts.loc[0]
answer_one()

V1        V2        V3        V4        V5        V6        V7  \
0      1.176563  0.323798  0.536927  1.047002 -0.368652 -0.728586  0.084678   
1      0.681109 -3.934776 -3.801827 -1.147468 -0.735540 -0.501097  1.038865   
2      1.140729  0.453484  0.247010  2.383132  0.343287  0.432804  0.093380   
3     -1.107073 -3.298902 -0.184092 -1.795744  2.137564 -1.684992 -2.015606   
4     -0.314818  0.866839 -0.124577 -0.627638  2.651762  3.428128  0.194637   
5     -0.713266  0.869132  0.330114  0.902275  0.520836 -0.537036  0.301955   
6      1.219060 -0.207708  0.782809  0.271655 -0.456658  0.414201 -0.675133   
7      0.683918  0.329216 -1.693025 -1.123644  2.662177  3.563731 -0.309291   
8     -1.127820  1.461342  0.526673 -0.158998  0.353158 -1.539196  0.727383   
9     -1.757794  0.821894  2.529482 -0.328198 -0.902062  0.739803 -0.119755   
10     0.349277 -2.539493  0.645773 -0.503734 -1.792852  0.986512 -0.927262   
11    -0.411810  1.023427  1.264103  0.025506  0.233213 -0.549449  0.582704   
12    -1.166636  1.389047  1.814434 -0.244077  0.326655 -0.173679  0.946169   
13    -1.156068  0.260288  1.156287 -1.628519 -0.336503 -1.493760 -0.080079   
14    -1.190038  0.649469  2.284449 -1.859697 -0.670685 -0.496543  0.064523   
15    -1.927453  1.827621 -7.019495  5.348303 -2.739188 -2.107219 -5.015848   
16    -1.747174  0.160249  2.376843  0.786738 -0.075605  0.571059 -0.743427   
17    -2.168001  0.033924  1.449290 -0.812047  1.002470 -1.138005 -0.037403   
18     1.095177  0.019951  0.802611  1.434379 -0.794724 -0.740487 -0.034083   
19     0.012405  0.323292  1.447131  0.752747 -0.103552 -0.174479 -0.129467   
20     1.240972  0.056519  0.356187  0.444614 -0.428139 -0.522949 -0.177292   
21    -1.623956 -0.036442  0.362751 -2.224536  0.095510 -0.092187 -0.463413   
22    -0.493634  0.921872  1.620242  0.902272 -0.063681 -0.470267  0.449907   
23     0.832463 -1.766357 -1.878930 -1.428497  1.353795  3.284183 -0.405475   
24    -0.864354 -5.195435 -0.145487 -0.036902 -3.374848  0.114814 -0.004674   
25     1.013856 -0.383698  1.281437  0.778703 -1.008979  0.373272 -0.773102   
26    -1.032545  1.933906 -3.733012  1.414886  1.008538 -0.583919 -0.313771   
27     0.132132  0.979695 -0.565781 -0.760869  1.188832 -0.258507  0.875670   
28     1.541905 -1.596027 -0.993563  0.728659 -0.790370  0.375218 -0.510420   
29    -0.730463  0.791686  0.372490 -0.440954  1.452256 -0.885030  0.766894   
...         ...       ...       ...       ...       ...       ...       ...   
21663  1.893277  0.299036 -0.138355  3.497436  0.410420  1.326585 -0.590901   
21664  0.491390 -3.935168 -2.061988 -1.687501 -1.495859  0.250427  0.302015   
21665  0.063739 -1.535378 -0.385704  1.542355 -0.627658 -0.273289  0.948604   
21666 -0.897571  1.165881  2.029559  1.037276 -0.373979  0.231473 -0.488755   
21667  1.293053  0.457969 -1.940450  0.173149  2.609570  3.014117 -0.269415   
21668 -1.834765 -0.949266  1.243113 -2.549263  1.865862  0.556664 -0.021561   
21669  0.648227 -0.591837 -0.022753  1.525897 -0.513242 -0.559400  0.558397   
21670  1.193230 -0.360918 -0.336591  0.588198  1.629746  4.383153 -1.054576   
21671 -0.928876  0.326916 -1.331394 -3.254378  2.736104  3.109749 -0.048090   
21672  1.154611  0.730975  0.229805  2.510698  0.268697 -0.544096  0.531158   
21673  1.239308 -2.616800 -1.652903 -0.149417 -1.405589 -0.644614 -0.051613   
21674  0.001428  0.916366 -0.497938 -0.712840  1.573434  0.723309  0.786018   
21675  0.265446  0.434850  1.007913 -0.667498  0.421526 -0.051506  0.591064   
21676 -1.482774 -1.141015  1.247646 -2.030778  0.606697 -1.187212 -0.071586   
21677 -0.725210  0.210455 -0.133458 -0.519537  0.295570  0.291036  0.325864   
21678 -1.116407  0.376521  3.316122  0.862534 -0.524907  0.652169 -0.011293   
21679  1.211549 -0.165301  1.040853  0.748805 -0.835772 -0.019663 -0.616143   
21680 -0.311558  1.107522  0.956259 -0.129188  0.528012 -0.516072  0.706706   
21681 -0.453495  0.500477 -0.559159 -0.334116  0.273782 -1.1900

In [7]:
# Use X_train, X_test, y_train, y_test for all of the following questions
from sklearn.model_selection import train_test_split

df = pd.read_csv('fraud_data.csv')

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

### Question 2

Using `X_train`, `X_test`, `y_train`, and `y_test` (as defined above), train a dummy classifier that classifies everything as the majority class of the training data. What is the accuracy of this classifier? What is the recall?

*This function should a return a tuple with two floats, i.e. `(accuracy score, recall score)`.*

In [8]:
def answer_two():
    from sklearn.dummy import DummyClassifier
    from sklearn.metrics import recall_score, accuracy_score
    dummy_majority = DummyClassifier(strategy = 'most_frequent').fit(X_train, y_train)
    y_dummy_predictions = dummy_majority.predict(X_test)
    a=accuracy_score(y_test, y_dummy_predictions)
    r=recall_score(y_test, y_dummy_predictions)
    
    # Your code here
    
    return (a,r)# Return your answer
answer_two()

(0.98525073746312686, 0.0)

### Question 3

Using X_train, X_test, y_train, y_test (as defined above), train a SVC classifer using the default parameters. What is the accuracy, recall, and precision of this classifier?

*This function should a return a tuple with three floats, i.e. `(accuracy score, recall score, precision score)`.*

In [9]:
def answer_three():
    from sklearn.metrics import recall_score, precision_score, accuracy_score
    from sklearn.svm import SVC
    
    svm=SVC().fit(X_train, y_train)
    svm_pred=svm.predict(X_test)
    a=accuracy_score(y_test, svm_pred)
    r=recall_score(y_test, svm_pred)
    p=precision_score(y_test, svm_pred)
    # Your code here
    
    return (a,r,p)# Return your answer
answer_three()


(0.99078171091445433, 0.375, 1.0)

### Question 4

Using the SVC classifier with parameters `{'C': 1e9, 'gamma': 1e-07}`, what is the confusion matrix when using a threshold of -220 on the decision function. Use X_test and y_test.

*This function should return a confusion matrix, a 2x2 numpy array with 4 integers.*

In [29]:
def answer_four():
    from sklearn.metrics import confusion_matrix
    from sklearn.svm import SVC

    svm=SVC(C=1e9,gamma=1e-07).fit(X_train, y_train)
    svm_pred=svm.predict(X_test)    
    y_pred = svm.fit(X_train, y_train).decision_function(X_test)
    y_pred_thre =y_pred>-220
    confusion_mc = confusion_matrix(y_test, y_pred_thre)
    # Your code here
    
    return confusion_mc# Return your answer
answer_four()

array([[5320,   24],
       [  14,   66]])

### Question 5

Train a logisitic regression classifier with default parameters using X_train and y_train.

For the logisitic regression classifier, create a precision recall curve and a roc curve using y_test and the probability estimates for X_test (probability it is fraud).

Looking at the precision recall curve, what is the recall when the precision is `0.75`?

Looking at the roc curve, what is the true positive rate when the false positive rate is `0.16`?

*This function should return a tuple with two floats, i.e. `(recall, true positive rate)`.*

In [11]:
def five():
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import precision_recall_curve
    from sklearn.metrics import roc_curve, auc
    lr=LogisticRegression().fit(X_train, y_train)
    lr_predicted = lr.predict(X_test)
    y_proba_lr = lr.fit(X_train, y_train).predict_proba(X_test) 
    y_scores_lr = lr.fit(X_train, y_train).decision_function(X_test)
    precision, recall, thresholds = precision_recall_curve(y_test, y_scores_lr)

    # Your code here 0.8 0.9
    
    return y_proba_lr[:,1]# Return your answer
five()

array([ 0.0012509 ,  0.00145784,  0.00249531, ...,  0.00213746,
        0.00041293,  0.00197765])

In [12]:
def answer_five():
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import precision_recall_curve
    from sklearn.metrics import roc_curve, auc
    lr=LogisticRegression().fit(X_train, y_train)
    lr_predicted = lr.predict(X_test)
    y_proba_lr = lr.fit(X_train, y_train).predict_proba(X_test) 
    y_scores_lr = lr.fit(X_train, y_train).decision_function(X_test)
    precision, recall, thresholds = precision_recall_curve(y_test, y_proba_lr[:,1])
    fpr_lr, tpr_lr, _ = roc_curve(y_test, y_proba_lr[:,1])
    roc_auc_lr = auc(fpr_lr, tpr_lr)
    # Your code here 0.8 
    
    return (0.8 , 0.9)# Return your answer
answer_five()

(0.8, 0.9)

### Question 6

Perform a grid search over the parameters listed below for a Logisitic Regression classifier, using recall for scoring and the default 3-fold cross validation.

`'penalty': ['l1', 'l2']`

`'C':[0.01, 0.1, 1, 10, 100]`

From `.cv_results_`, create an array of the mean test scores of each parameter combination. i.e.

|      	| `l1` 	| `l2` 	|
|:----:	|----	|----	|
| **`0.01`** 	|    ?	|   ? 	|
| **`0.1`**  	|    ?	|   ? 	|
| **`1`**    	|    ?	|   ? 	|
| **`10`**   	|    ?	|   ? 	|
| **`100`**   	|    ?	|   ? 	|

<br>

*This function should return a 5 by 2 numpy array with 10 floats.* 

*Note: do not return a DataFrame, just the values denoted by '?' above in a numpy array.*

In [23]:
def answer_six(): 
    from sklearn.model_selection import GridSearchCV
    from sklearn.linear_model import LogisticRegression
    lr=LogisticRegression()
    grid_values = {'penalty': ['l1', 'l2'],'C': [0.01, 0.1, 1, 10, 100]}

    # default metric to optimize over grid parameters: accuracy
    grid_clf = GridSearchCV(lr, scoring='recall', param_grid = grid_values)

    # default metric to optimize over grid parameters: accuracy
    grid_clf.fit(X_train, y_train)
    y_decision_fn_scores = grid_clf.decision_function(X_test)
    
    # Your code here
    
    return grid_clf.cv_results_['mean_test_score'].reshape(5,2) # Return your answer
answer_six()


array([[ 0.66666667,  0.76086957],
       [ 0.80072464,  0.80434783],
       [ 0.8115942 ,  0.8115942 ],
       [ 0.80797101,  0.8115942 ],
       [ 0.80797101,  0.80797101]])

In [ ]:
# Use the following function to help visualize results from the grid search
def GridSearch_Heatmap(scores):
    %matplotlib notebook
    import seaborn as sns
    import matplotlib.pyplot as plt
    plt.figure()
    sns.heatmap(scores.reshape(5,2), xticklabels=['l1','l2'], yticklabels=[0.01, 0.1, 1, 10, 100])
    plt.yticks(rotation=0);

#GridSearch_Heatmap(answer_six())